###############################################################################
# Log forwarder configuration winlog example                                  #
# Source: Windows event log                                                   #
###############################################################################
logs:
  - name: windows-security
    attributes:
      environment: prod
    winlog:
      channel: Security
  - name: windows-application
    attributes:
      environment: prod
    winlog:
      channel: Application
  - name: windows-system
    attributes:
      environment: prod
    winlog:
      channel: System
