# escape=`

ARG IMG_SERVERCORE2022
FROM ${IMG_SERVERCORE2022}

# Component and role install
COPY "setup\\install" "C:\\setup"
RUN xcopy /E /Y "c:\\setup\\assets" "C:\\"
RUN c:\setup\setup.ps1;

# CHEF
COPY "setup\\chef" "C:\\setup"
RUN xcopy /E /Y "c:\\setup\\assets" "C:\\"
RUN c:\setup\setup.ps1;

# Basic setup
COPY "setup\\base" "C:\\setup"
RUN xcopy /E /Y "c:\\setup\\assets" "C:\\"
RUN c:\setup\setup.ps1;

# Perfmon
COPY "setup\\perfmon" "C:\\setup"
RUN xcopy /E /Y "c:\\setup\\assets" "C:\\"
RUN c:\setup\setup.ps1;

RUN Remove-Item -Recurse -Force "c:\setup\";


