services:
  mssql:
    stop_grace_period: 60s
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 3G
        reservations:
          cpus: '0.5'
          #memory: 2G
    build:
      context: .
      args:
        IMG_SERVERCORE2022: ${IMG_SERVERCORE2022}
        IMG_SQLSERVER2022AS: ${IMG_SQLSERVER2022AS}
        IMG_SQLSERVER2022BASE: ${IMG_SQLSERVER2022BASE}
        IMG_SQLSERVER2022K8S: ${IMG_SQLSERVER2022K8S}
    image: ${IMG_SQLSERVER2022K8S}
    volumes:
      - "f:/databases/example/data:d:"
    networks:
      container_default:
        ipv4_address: 172.18.8.8
    environment:
      - MSSQL_ADMIN_USERNAME=sa
      - MSSQL_ADMIN_PWD_PROTECT=sapwd
      - MSSQL_LIFECYCLE=PERSISTENT
      - MSSQL_SPCONFIGURE=max degree of parallelism:1;backup compression default:1
      - MSSQL_SPCONFIGURERESTART=0
      - MSSQL_PATH_DATA=d:\data
      - MSSQL_PATH_LOG=d:\log
      - MSSQL_PATH_BACKUP=d:\backup
      - MSSQL_PATH_CONTROL=d:\control
      - MSSQL_PATH_SYSTEM=d:\system
      - MSSQL_BACKUP_RELEASEMEMORY=400
      - SBS_TEMPORARY=d:\temp
      - SBS_ENTRYPOINTERRORACTION=Stop
      - SBS_GETWINEVENT=[{LogName:["Application"],ProviderName:"*",Level:[1]},{LogName:["Application"], ProviderName:"SbsContainer", Level:[1,2,3,4]}]
      - SBS_GETEVENTLOG=[{LogName:"Application", Source:"*", MinLevel:"Information"}, {LogName:"System", Source:"*", MinLevel:"Warning"}]
networks:
  container_default:
    external: true
