# Backup base lifecyle: there is no persistent state, backup restored when pod
# spins up, and backup done when it tears down.
services:
  mssql:
    stop_grace_period: 60s
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 3G
        reservations:
          cpus: '0.5'
          #memory: 2G
    build:
      context: .
      args:
        IMG_SERVERCORE2022: ${IMG_SERVERCORE2022}
        IMG_SQLSERVER2022AS: ${IMG_SQLSERVER2022AS}
        IMG_SQLSERVER2022BASE: ${IMG_SQLSERVER2022BASE}
        IMG_SQLSERVER2022K8S: ${IMG_SQLSERVER2022K8S}
    image: ${IMG_SQLSERVER2022K8S}
    volumes:
      - "c:/datavolume:d:"
    networks:
      container_default:
        ipv4_address: 172.18.8.8
    environment:
      # Temporary workaround to make scheduled tasks work
      - SBS_PROMOTE_ENV_REGEX=^SBS_|^MSSQL_
      # Admin credentials
      - MSSQL_ADMIN_USERNAME=sa
      - MSSQL_ADMIN_PWD_PROTECT=sapwd
      # Backup based lifecyle. Restore on pod startup, backup during usage and final backup when pod closes. High
      # downtime when moving pods, but good to test backup behavior. Can perfectly
      # work on dev environments with good underlying NVME hardware where these
      # restores take 4 min for 70GB backups. With smaller databases, timings become
      # much more reasonable.
      - MSSQL_LIFECYCLE=BACKUP
      - SBS_INITASYNC=True
      - SBS_DEBUG=True
      # We need to configure backup schedules
      - 'MSSQL_JOB_Full={"Job":"MssqlBackup - FULL", "Enabled": true, "Schedules": [{"Schedule": "Full weekly", "FrequencyType": "Weekly", "FrequencyInterval": "Saturday", "FrequencySubdayType": "Once", "StartTime": "230000"}]}'
      - 'MSSQL_JOB_Log={"Job":"MssqlBackup - LOG", "Enabled": true, "Schedules": [{"Schedule": "Every 5 minutes", "FrequencyType": "Daily", "FrequencyInterval": "EveryDay", "StartTime": "000000", "EndTime": "235959", "FrequencySubdayType": "Minutes", "FrequencySubdayInterval": 5}]}'
      - 'MSSQL_JOB_Diff={"Job":"MssqlBackup - DIFF", "Enabled": true, "Schedules": [{"Schedule": "Daily", "FrequencyType": "Daily", "FrequencyInterval": "EveryDay", "StartTime": "230000"}]}'
      - 'MSSQL_JOB_CommandLogCleanup={"Job":"CommandLog Cleanup", "Enabled": true, "Schedules": [{"Schedule": "Full weekly", "FrequencyType": "Weekly", "FrequencyInterval": "Friday", "FrequencySubdayType": "Once", "StartTime": "220000"}]}'
      - 'MSSQL_JOB_MssqlCleanBackups={"Job":"MssqlBackup - CLEAN", "Enabled": true, "Schedules": [{"Schedule": "Every 6 hours", "FrequencyType": "Daily", "FrequencyInterval": "EveryDay", "StartTime": "000000", "EndTime": "235959", "FrequencySubdayType": "Hours", "FrequencySubdayInterval": 6}]}'
      - 'MSSQL_JOB_LtsAzCopy={"Job":"MssqlBackup - LTS AzCopy", "Enabled": true, "Schedules": [{"Schedule": "Every 2 hours", "FrequencyType": "Daily", "FrequencyInterval": "EveryDay", "StartTime": "000000", "EndTime": "235959", "FrequencySubdayType": "Hours", "FrequencySubdayInterval": 2}]}'
      - 'MSSQL_JOB_DeleteBackupHistory={"Job":"sp_delete_backuphistory", "Enabled": true, "Schedules": [{"Schedule": "Daily", "FrequencyType": "Daily", "FrequencyInterval": "EveryDay", "StartTime": "190000"}]}'
      - 'MSSQL_JOB_PurgeJobHistory={"Job":"sp_purge_jobhistory", "Enabled": true, "Schedules": [{"Schedule": "Daily", "FrequencyType": "Daily", "FrequencyInterval": "EveryDay", "StartTime": "200000"}]}'
      - 'MSSQL_JOB_OutputFileCleanup={Job: Output File Cleanup, Enabled: true, Schedules: [{Schedule: Full weekly, FrequencyType: Weekly, FrequencyInterval: Thursday, FrequencySubdayType: Once, StartTime: 220000}]}'
      - 'MSSQL_JOB_MssqlIndexOptimize={Job: "MSSQL Index Optimize", Enabled: true, Schedules: [{Schedule: Full weekly, FrequencyType: Weekly, FrequencyInterval: "Saturday", FrequencySubdayType: Once, StartTime: 010000}]}'
      # Automated certificates
      #- MSSQL_BACKUP_CERT=AUTO
      # Log backup criteria
      - MSSQL_BACKUP_LOGSIZESINCELASTBACKUP=200
      - MSSQL_BACKUP_TIMESINCELASTLOGBACKUP=600
      # Backup retention
      - MSSQL_BACKUP_CLEANUPTIME_LOG=48
      - MSSQL_BACKUP_CLEANUPTIME_DIFF=72
      - MSSQL_BACKUP_CLEANUPTIME_FULL=128
      # Other stuff
      - MSSQL_SPCONFIGURE=max degree of parallelism:1;backup compression default:1
      - MSSQL_SPCONFIGURERESTART=0
      - MSSQL_PATH_DATA=d:\data
      - MSSQL_PATH_LOG=d:\log
      - MSSQL_PATH_BACKUP=d:\backup
      - MSSQL_CLEARDATAPATHS=True
      # Database info
      - MSSQL_DB_NAME=mytestdatabase
      - MSSQL_DB_RECOVERYMODEL=FULL
      - SBS_TEMPORARY=d:\temp
      - SBS_ENTRYPOINTERRORACTION=Stop
      # Output in the entrypoint loop
      - SBS_GETWINEVENT=[{LogName:["Application"],ProviderName:"*",Level:[1]},{LogName:["Application"], ProviderName:"SbsContainer", Level:[1,2,3,4]}]
      - SBS_GETEVENTLOG=[{LogName:"Application", Source:"*", MinLevel:"Information"}, {LogName:"System", Source:"*", MinLevel:"Warning"}]
      # Shutdown timeout
      - SBS_SHUTDOWNTIMEOUT=60
      - MSSQL_MAXMEMORY=300
networks:
  container_default:
    external: true
