# escape=`

ARG IMG_SQLSERVER2022BASE
FROM ${IMG_SQLSERVER2022BASE}

SHELL ["powershell.exe"]

COPY "setup\\base" "C:\\setup"
RUN xcopy /E /Y "c:\\setup\\assets" "C:\\"
RUN c:\setup\setup.ps1
RUN Remove-Item -Path c:\setup -Recurse -Force;

COPY "setup\\backups" "C:\\setup"
RUN xcopy /E /Y "c:\\setup\\assets" "C:\\"
RUN c:\setup\setup.ps1
RUN Remove-Item -Path c:\setup -Recurse -Force;

SHELL ["cmd.exe"]