version: 2.1

orbs:
  win: circleci/windows@2.4.0 # Use the Windows orb for PowerShell support

jobs:
  build:
    executor:
      name: win/default # Specify the Windows executor
    steps:
      - add_ssh_keys
          fingerprints:
            - "SHA256:MWTM5Rby1BQ0EaBqiDPstXyPtvro7DZoAlnoKwz7I/k"
      - checkout
      - run:
          name: Install Docker
          command: choco install docker-desktop -y
      - run:
          name: Build Docker Images
          command: |
            .\imagenames.ps1 "myrepo/"
            .\buildall.ps1
workflows:
  version: 2
  build-and-push:
    jobs:
      - build
