services:
  servercore:
    stop_grace_period: 40s
    build:
      context: .
      args:
        IMG_SERVERCORE2022: ${IMG_SERVERCORE2022}
        IMG_SQLSERVER2022AS: ${IMG_SQLSERVER2022AS}
        IMG_SQLSERVER2022BASE: ${IMG_SQLSERVER2022BASE}
        IMG_SQLSERVER2022K8S: ${IMG_SQLSERVER2022K8S}
    image: ${IMG_SERVERCORE2022}
    environment:
      - SBS_DEBUG=True
      - SBS_CONTAINERTIMEZONE=Alaskan Standard Time
      - WER_ENABLE=True
      - WER_DUMPFOLDER=C:\CrashDumps
      - WER_DUMPCOUNT=10
      - WER_DUMPTYPE=2
      - WER_CUSTOMDUMPFLAGS=0
    networks:
      - container_default
    # Environment completely wiped out on purpose, to test
    # scripts resiliency to null/empty
networks:
  container_default:
    external: true
