version: "3.7"
services:
  servercore:
    stop_grace_period: 40s
    build:
      context: .
      args:
        IMG_SERVERCORE2022: ${IMG_SERVERCORE2022}
        IMG_SQLSERVER2022AS: ${IMG_SQLSERVER2022AS}
        IMG_SQLSERVER2022BASE: ${IMG_SQLSERVER2022BASE}
        IMG_SQLSERVER2022K8S: ${IMG_SQLSERVER2022K8S}
    image: ${IMG_SERVERCORE2022}
    environment:
      - SBS_MONITORLOGCONFIGURATIONS=[{LogName:["Application"],ProviderName:"*",Level:[1]},{LogName:["Application"], ProviderName:"SbsContainer", Level:[1,2,3,4]}]
    networks:
      - container_default
    # Environment completely wiped out on purpose, to test
    # scripts resiliency to null/empty
networks:
  container_default:
    external: true
