# escape=`
FROM mcr.microsoft.com/windows/servercore:ltsc2022

# https://github.com/microsoft/dotnet-framework-docker/blob/main/src/runtime/4.8.1/windowsservercore-ltsc2022/Dockerfile
ENV `
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true `
    COMPLUS_RUNNING_IN_CONTAINER=1 `
    COMPLUS_NGenProtectedProcess_FeatureEnabled=0

# https://github.com/microsoft/dotnet-framework-docker/blob/main/src/runtime/4.8/windowsservercore-ltsc2022/Dockerfile
RUN `
    # Ngen top of assembly graph to optimize a set of frequently used assemblies
    %windir%\Microsoft.NET\Framework64\v4.0.30319\ngen install "Microsoft.PowerShell.Utility.Activities, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" `
    # To optimize 32-bit assemblies, uncomment the next line
    # && %windir%\Microsoft.NET\Framework\v4.0.30319\ngen install "Microsoft.PowerShell.Utility.Activities, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" `
    && %windir%\Microsoft.NET\Framework64\v4.0.30319\ngen update `
    && %windir%\Microsoft.NET\Framework\v4.0.30319\ngen update

# Install 2.9.0 Roslyn compilers - Download and extract
RUN curl -fSLo microsoft.net.compilers.2.9.0.zip https://api.nuget.org/packages/microsoft.net.compilers.2.9.0.nupkg `
    && mkdir C:\RoslynCompilers `
    && tar -C C:\RoslynCompilers -zxf microsoft.net.compilers.2.9.0.zip `
    && del microsoft.net.compilers.2.9.0.zip

# Install 2.9.0 Roslyn compilers - csc.exe
RUN %windir%\Microsoft.NET\Framework64\v4.0.30319\ngen install C:\RoslynCompilers\tools\csc.exe /ExeConfig:C:\RoslynCompilers\tools\csc.exe

# Install 2.9.0 Roslyn compilers - vbc.exe
RUN %windir%\Microsoft.NET\Framework64\v4.0.30319\ngen install C:\RoslynCompilers\tools\vbc.exe /ExeConfig:C:\RoslynCompilers\tools\vbc.exe

# Install 2.9.0 Roslyn compilers - VBCSCompiler.exe
RUN %windir%\Microsoft.NET\Framework64\v4.0.30319\ngen install C:\RoslynCompilers\tools\VBCSCompiler.exe /ExeConfig:C:\RoslynCompilers\tools\VBCSCompiler.exe

# Install 3.6.0 Roslyn compilers - Download and extract
RUN curl -fSLo microsoft.net.compilers.3.6.0.zip https://api.nuget.org/packages/microsoft.net.compilers.3.6.0.nupkg `
    && mkdir C:\RoslynCompilers-3.6.0 `
    && tar -C C:\RoslynCompilers-3.6.0 -zxf microsoft.net.compilers.3.6.0.zip `
    && del microsoft.net.compilers.3.6.0.zip

# Install 3.6.0 Roslyn compilers - csc.exe
RUN %windir%\Microsoft.NET\Framework64\v4.0.30319\ngen install C:\RoslynCompilers-3.6.0\tools\csc.exe /ExeConfig:C:\RoslynCompilers-3.6.0\tools\csc.exe

# Install 3.6.0 Roslyn compilers - vbc.exe
RUN %windir%\Microsoft.NET\Framework64\v4.0.30319\ngen install C:\RoslynCompilers-3.6.0\tools\vbc.exe /ExeConfig:C:\RoslynCompilers-3.6.0\tools\vbc.exe

# Install 3.6.0 Roslyn compilers - VBCSCompiler.exe
RUN %windir%\Microsoft.NET\Framework64\v4.0.30319\ngen install C:\RoslynCompilers-3.6.0\tools\VBCSCompiler.exe /ExeConfig:C:\RoslynCompilers-3.6.0\tools\VBCSCompiler.exe

ENV ROSLYN_COMPILER_LOCATION=C:\RoslynCompilers-3.6.0\tools

SHELL ["powershell.exe"]

RUN $global:ErrorActionPreference = 'Stop'; `
    mkdir 'c:\Program Files\LogMonitor'; `
    Invoke-WebRequest -Uri "https://github.com/microsoft/windows-container-tools/releases/download/v2.0.2/LogMonitor.exe" -OutFile 'c:\Program Files\LogMonitor\LogMonitor.exe'

# Change the default to something a little bit larger than the default 5s.... 15s
# https://github.com/dotnet/runtime/issues/63709
RUN $global:ErrorActionPreference = 'Stop'; `
    reg add hklm\system\currentcontrolset\services\cexecsvc /v ProcessShutdownTimeoutSeconds /t REG_DWORD /d 15; `
    reg add hklm\system\currentcontrolset\control /v WaitToKillServiceTimeout /t REG_SZ /d 15000 /f;

RUN $global:ErrorActionPreference = 'Stop'; `
    Add-WindowsCapability -Online -Name OpenSSH.Server

RUN $global:ErrorActionPreference = 'Stop'; `
    Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

COPY "setup\\external" "C:\\setup"
RUN xcopy /E /Y "c:\\setup\\assets" "C:\\"
RUN echo "setup\\external";c:\setup\setup.ps1
RUN Remove-Item -Path c:\setup -Recurse -Force;

COPY "setup\\logrotate" "C:\\setup"
RUN xcopy /E /Y "c:\\setup\\assets" "C:\\"
RUN echo "setup\\logrotate";c:\setup\setup.ps1
RUN Remove-Item -Path c:\setup -Recurse -Force;

COPY "setup\\base" "C:\\setup"
RUN xcopy /E /Y "c:\\setup\\assets" "C:\\"
RUN echo "setup\\base";c:\setup\setup.ps1
RUN Remove-Item -Path c:\setup -Recurse -Force;

ENTRYPOINT ["c:\\Program Files\\LogMonitor\\LogMonitor.exe", "/CONFIG", "c:\\logmonitor\\config.json", "powershell.exe", "-File", "C:\\entrypoint\\entrypoint.ps1" ]