services:
  mssql:
    stop_grace_period: 40s
    build:
      context: .
      args:
        IMG_SERVERCORE2022: ${IMG_SERVERCORE2022}
        IMG_SQLSERVER2017BASE: ${IMG_SQLSERVER2017BASE}
        MSSQL2017INSTALL_ISO_URL: ${MSSQL2017INSTALL_ISO_URL}
        MSSQL2017INSTALL_CU_URL: ${MSSQL2017INSTALL_CU_URL}
        MSSQL2017INSTALL_CUFIX_URL: ${MSSQL2017INSTALL_CUFIX_URL}
        TEMP: ${BUILD_TEMP}
    image: ${IMG_SQLSERVER2017BASE}
    networks:
      container_default:
        ipv4_address: 172.18.8.8
    environment:
      - MSSQL_ADMIN_PWD_PROTECT=testpassword
      - MSSQL_SERVERNAME=k8s
      - SBS_ENTRYPOINTERRORACTION=Stop
      - SBS_DEBUG=True
networks:
  container_default:
    driver: nat  # Usa 'nat' para redes de Windows
    ipam:
      config:
        - subnet: 172.18.0.0/16  # Asegúrate de que esta subred incluya 172.18.8.86
