# escape=`

ARG IMG_SERVERCORE2022
FROM ${IMG_SERVERCORE2022}

ARG MSSQL2019INSTALL_ISO_URL
ARG MSSQL2019INSTALL_CU_URL
ARG MSSQL2019INSTALL_CUFIX_URL

ENV MSSQL2019INSTALL_ISO_URL=$MSSQL2019INSTALL_ISO_URL
ENV MSSQL2019INSTALL_CU_URL=$MSSQL2019INSTALL_CU_URL
ENV MSSQL2019INSTALL_CUFIX_URL=$MSSQL2019INSTALL_CUFIX_URL

SHELL ["powershell.exe"]

# https://learn.microsoft.com/en-us/sql/database-engine/install-windows/install-sql-server-from-the-command-prompt?view=sql-server-ver16#ProperUse

# TODO: De momento ponemos la descarga como un paso independiente, para evitar
# tener que descargarla todo el rato, pero para reducir el tamaño de la imagen,
# la descarga, instalación y luego borrado de la ISO deben hacerse en un solo step
# para que entre en un layer
# RUN curl -o C:\SQLServer2019-x64-ENU-Dev.iso https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SQLServer2019-x64-ENU-Dev.iso;

COPY "setup\\install" "C:\\setup"
RUN xcopy /E /Y "c:\\setup\\assets" "C:\\"
RUN c:\setup\setup.ps1
RUN Remove-Item -Path c:\setup -Recurse -Force;

COPY "setup\\tools" "C:\\setup"
RUN xcopy /E /Y "c:\\setup\\assets" "C:\\"
RUN c:\setup\setup.ps1
RUN Remove-Item -Path c:\setup -Recurse -Force;

COPY "setup\\base" "C:\\setup"
RUN xcopy /E /Y "c:\\setup\\assets" "C:\\"
RUN echo "setup/base"; c:\setup\setup.ps1
RUN Remove-Item -Path c:\setup -Recurse -Force;

SHELL ["cmd.exe"]
