services:
  mssql:
    stop_grace_period: 40s
    build:
      context: .
      args:
        IMG_SERVERCORE2022: ${IMG_SERVERCORE2022}
        IMG_SQLSERVER2022AS: ${IMG_SQLSERVER2022AS}
        IMG_SQLSERVER2022BASE: ${IMG_SQLSERVER2022BASE}
        IMG_SQLSERVER2022K8S: ${IMG_SQLSERVER2022K8S}
        MSSQLINSTALL_ISO_URL: ${MSSQLINSTALL_ISO_URL}
        MSSQLINSTALL_CU_URL: ${MSSQLINSTALL_CU_URL}
        MSSQLINSTALL_CUFIX_URL: ${MSSQLINSTALL_CUFIX_URL}
        TEMP: ${BUILD_TEMP}
    image: ${IMG_SQLSERVER2022BASE}
    networks:
      container_default:
        ipv4_address: 172.18.8.8
    environment:
      - MSSQL_ADMIN_PWD_PROTECT=testpassword
      - MSSQL_SERVERNAME=k8s
      - SBS_ENTRYPOINTERRORACTION=Stop
      - SBS_DEBUG=True
networks:
  container_default:
    external: true
