# https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-config/
# Este fichero está planteado en tres integraciones con tres
# frecuencias diferentes para ahorrar datos.
integrations:
# Integración de solo inventario, no requiere mucha frecuencia...
- name: nri-mssql
  env:
    HOSTNAME:
    USERNAME:
    PASSWORD:
    PORT:
    INSTANCE:
    ENABLE_SSL: true
    TRUST_SERVER_CERTIFICATE: true
    TIMEOUT: 8
    INVENTORY: true
  interval: 60s
  labels:
    environment:
    role: mssql
  inventory_source: config/mssql
# Integración de uso de recursos por base de datos, importante
# para diagnóstico
- name: nri-mssql
  env:
    HOSTNAME:
    USERNAME:
    PASSWORD:
    PORT:
    INSTANCE:
    ENABLE_SSL: true
    TRUST_SERVER_CERTIFICATE: true
    TIMEOUT: 8
    CUSTOM_METRICS_CONFIG: 'C:\Program Files\New Relic\newrelic-infra\mssqlquery\mssql-custom-query.yml'
    ENABLE_BUFFER_METRICS: false
    ENABLE_DATABASE_RESERVE_METRICS: false
    METRICS: true
  interval: 25s
  labels:
    environment:
    role: mssql
  inventory_source: config/mssql
# Intgración de consultas lentas, esto lleva mucha información duplicada en cada llamada
# enviamos poco dato.
- name: nri-mssql
  env:
    HOSTNAME:
    USERNAME:
    PASSWORD:
    PORT:
    INSTANCE:
    ENABLE_SSL: true
    TRUST_SERVER_CERTIFICATE: true
    TIMEOUT: 8
    CUSTOM_METRICS_CONFIG: 'C:\Program Files\New Relic\newrelic-infra\mssqlquery\mssql-custom-query-daily.yml'
    ENABLE_BUFFER_METRICS: false
    ENABLE_DATABASE_RESERVE_METRICS: false
    METRICS: true
  interval: 3600s
  labels:
    environment:
    role: mssql
  inventory_source: config/mssql